### ISSUE TITLE
Could not fetch the CDN data: stream_not_started 

### ISSUE THREAD

**Issue by frelev** [lindell/home-assistant-tv4-play#2]
I´m trying to use this and send TV4 to my Samsung TV. But when running this in developer tools -> Services 
```
program_name: nyhetsmorgon
entity_id: media_player.the_frame
```
I get:

`  File "/home/hass/.homeassistant/custom_components/tv4_play/__init__.py", line 30, in play_suggested
    video_url = get_video_url(get_suggested_episode(program_name))
  File "/home/hass/.homeassistant/custom_components/tv4_play/video_url_fetch/video_fetch.py", line 16, in get_video_url
    "Could not fetch the CDN data: {}".format(data['errorCode'])
Exception: Could not fetch the CDN data: stream_not_started
`

Any idea how to fix it?

**Comment by lindell** [comment]
The suggested stream on nyhetsmorgon is always either the current stream or tomorrows. Since you are running it in the afternoon (I presume), the suggested stream (tommorows program) has not yet started.
Was the expectation to play this mornings program? In that case I can look into if it's easy to get that data from the API.

**Comment by frelev** [comment]
> The suggested stream on nyhetsmorgon is always either the current stream or tomorrows. Since you are running it in the afternoon (I presume), the suggested stream (tommorows program) has not yet started.
> Was the expectation to play this mornings program? In that case I can look into if it's easy to get that data from the API.

OK I see, yes I installed it right now and got this. I was expecting to get the latest show aired (and live show if it was running) so yes this mornings program.
No big deal, It´s enough if live-tv works I assume...

**Comment by lindell** [comment]
Looking at the TV4 API again, I remembered why this isn't implemented. It's because the information doesn't exist (for live programs like nyhetsmorgon at least).

![image](https://user-images.githubusercontent.com/284868/71768243-b756ec80-2f14-11ea-85b0-ebf4c0447d0c.png)

I will close this issue since it seems you don't need this feature and it is currently unsolvable.
